export const navType = {
  bar: "text-[15px] font-normal",
  barActive: "text-[15px] font-semibold",
  groupLabel: "text-muted-foreground text-[13px] font-normal",
  primaryLink: "text-2xl font-semibold tracking-tight",
  secondaryLink: "text-[13px] font-semibold",
  body: "text-[13px] font-normal",
  mobileLink: "text-sm font-medium",
  drawerPrimary: "text-[15px] font-semibold",
  drawerHeading: "text-lg font-bold",
  mobileTab: "text-[15px] font-medium",
  mobileTabActive: "text-[15px] font-bold",
  bottomTab: "text-[12px] font-medium",
  bottomTabActive: "text-[12px] font-semibold",
  badge: "text-[10px] font-bold",
} as const;
